services:
  postgres:
    image: postgres:16-alpine
    container_name: bajaj-repuestos-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: bajaj
      POSTGRES_PASSWORD: bajaj123
      POSTGRES_DB: bajaj_repuestos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
